# Generated by Django 4.0.2 on 2022-03-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='title',
        ),
    ]
