# Generated by Django 4.0.2 on 2022-03-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jum', '0006_alter_application_user_alter_application_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(height_field='height_field', upload_to='avatars', width_field='width_field'),
        ),
    ]
