# Generated by Django 4.0.2 on 2022-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jum', '0007_alter_specialty_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
