# Generated by Django 4.0.2 on 2022-09-16 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jum', '0016_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('NL', 'Не ищу работу'),
                                                     ('SF', 'Рассматриваю предложения'),
                                                     ('AL', 'Ищу работу')], max_length=50)),
                ('salary', models.IntegerField()),
                ('specialty', models.CharField(max_length=30)),
                ('grade', models.CharField(choices=[('IN', 'Интерн'),
                                                    ('JN', 'Джуниор'),
                                                    ('MD', 'Мидл'),
                                                    ('SN', 'Сеньер'),
                                                    ('TL', 'Тимлид')], max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.TextField(max_length=300)),
                ('portfolio', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='resume',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
