# Generated by Django 4.1.1 on 2022-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jum', '0017_alter_application_written_phone_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company/default.png', upload_to='company'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.TextField(choices=[('NL', 'Не ищу работу'), ('SF', 'Рассматриваю предложения'), ('AL', 'Ищу работу')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.TextField(max_length=30),
        ),
    ]
