# Generated by Django 4.1.1 on 2022-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jum', '0018_alter_company_logo_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('NL', 'Не ищу работу'), ('SF', 'Рассматриваю предложения'), ('AL', 'Ищу работу')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(max_length=30),
        ),
    ]
